### ISSUE TITLE
Allow data stores to prepare accessing inert resources

### ISSUE THREAD

**Issue by forman** [xcube-dev/xcube#1093]
**Is your feature request related to a problem? Please describe.**

Some data APIs provide only limited data access performance. Hence, the xcube data store's `store.open_data(data_id, ...)` approach doesn't apply well because (A) the method is blocking meaning it is not async, and (2) it may take long time before it returns. The reasons for data APIs to be slow are manifold: intended access is by file download, access is bandwidth limited, or not allowing for subsetting.

**Describe the solution you'd like**

Give users the opportunity to prepare selected datasets for faster access. Therefore, the data store interface should be extended by a new method `preload_data()` that allows for preparing selected datasets for faster access. Of course, how this is done depends heavily on the specific data API. However, the data store framework could help implementing such preparations, e.g., by providing the means to download and cache data in generic filesystems (by the use of `fsspec`).
The input to the methods should be the data identifiers to be prepared, and data store specific preload parameters.
The return value of `preload_data()` should be a handle that represents the preloading process.
A second method should allow for describing allowed parameters passed to the `preload_data()`: `get_preload_params_schema()`. New method signarures:

```python
def preload_data(self, *data_ids: str, **preload_params: Any) -> PreloadHandle:
    """Preaload data for faster access."""
    return NullPreloadHandle()  # No effect

def get_preload_data_params(self) -> JsonObjectSchema:
    """Get the JSON schema that describes the parameters passed to `preload_data()`."""
    return JsonObjectSchema(additional_properties=False)
```

The `PreloadHandle` interface:

```python
@property
def is_cancelled() -> bool:
    """Whether the preload process has been cancelled."""

def cancel():
    """Cancel the preload process."""

@property
def is_closed() -> bool:
    """Whether the preload process has been closed."""

def close():
   """Close the preload process and release any bound resources.""""

@property
def progress() -> float:
   """Get the progress as a number in the range 0 to 1.""""

def subscribe(listener: Callable[[str, float, str], None]) -> Callable[[], None]:
   """Subscribe to state changes of the preload process.

   Args:
       listener: a listener that receives status, progress, and a message
   Returns: 
       A function to unsubscribe from the preload process.
    """
``` 

The `PreloadHandle` interface should also have an intuitive Jupyter Notebook representation to let user observe a long-running preload process.

**Comment by forman** [comment]
FYI @konstntokas @b-yogesh

**Comment by b-yogesh** [comment]
Thanks @forman for defining this in detail. 
I have a few questions
- `PreloadHandle.progress` - you mention that this should return a float from 0 to 1, but how do we quantify the waiting time + download + extraction for a tuple of data_ids? And what does this number mean to the user?
- `close` vs `cancel` - what is the difference here? When to use close and the expected behavour? If the preload is in the progress and the user calls `close`, does it mean we have to internally first `cancel` the preload and then release the resources?
- If the user calls `cancel`, do we cancel the preload activities for all the data_ids? What if some of the requests are already completed? Or, do we add parameters to the `cancel` method for cancelling requests of an individual data_id?

**Comment by forman** [comment]
@b-yogesh 

> * `PreloadHandle.progress` - you mention that this should return a float from 0 to 1, but how do we quantify the waiting time + download + extraction for a tuple of data_ids? 

This is up to the specific implementation. Naive implementation would compute it by `current_data_index / (len(data_ids) - 1)`. But usually you can achieve a higher progress resolution by recording progress within preloading of individual data items.

> And what does this number mean to the user?

The preload process is `100 * progress` percent completed.

> * `close` vs `cancel` - what is the difference here? When to use close and the expected behavour? If the preload is in the progress and the user calls `close`, does it mean we have to internally first `cancel` the preload and then release the resources?

I believe the original idea I had was allowing for implementing the `PreloadHandle` as a context manager:

```Python
# Blocks until preloading is done then executes the code block, then closes.
with store.preload("my_id_1", "my_id_2"):  
    ds1 = store.open_data("my_id_1")
    ds2 = store.open_data("my_id_2")
    # do something with ds1, ds2
```

vs.

```Python
# Non-blocking call. 
plh = store.preload("my_id_1", "my_id_2")

# Use the handle to observe the preload process. E.g. show progress bar in JL.
# If it takes to long for your your taste, call plh.cancel().

ds1 = store.open_data("my_id_1")
ds2 = store.open_data("my_id_2")
# do something with ds1, ds2

# Call close when you are done to release any resource, e.g., temp files.
plh.close()
```

> * If the user calls `cancel`, do we cancel the preload activities for all the data_ids? What if some of the requests are already completed? Or, do we add parameters to the `cancel` method for cancelling requests of an individual data_id?

Cancellation refers to the handle, hence the process covering all the passed `data_ids`.
