### ISSUE TITLE
Allow using alpha in cpd files 

### ISSUE THREAD

**Issue by luca-moscatelli** [xcube-dev/xcube#932]
my problem is this : i have this cpd file
 color0=12, 224, 47
color1=246, 236, 22
color2=255,28, 21
numPoints=3
sample0=0
sample1=1
sample2=2
It works well, but if I use alpha like color0 = 12, 224, 47, 0, the color is corrupted and the result goes from black to white. Did I make a mistake or is it a problem with xcube?"

**Comment by forman** [comment]
Hi @luca-moscatelli, thanks for reporting. Have a look into the logs. You should actually see an error `Illegal SNAP *.cpd format:`. Unfortunately, color values must be `R, G, B`. For no good reason actually. I relabel this issue and rename it. Hope this ok for you.
