### ISSUE TITLE
test_gen.py extremely slow on GitHub Actions

### ISSUE THREAD

**Issue by pont-us** [xcube-dev/xcube#946]
**Describe the bug**

GitHub Actions unit test runs are very slow (usually around 40 minutes, versus ~12 minutes per platform on AppVeyor and ~5 minutes on my local machine). Closer inspection of the logs reveals that around 35 of these 40 minutes are spent in one test module -- `test/core/gen/test_gen.py`. For instance, look at the logs for [this](https://github.com/dcs4cop/xcube/actions/runs/8237024354/job/22524820335) test run:

```text
Mon, 11 Mar 2024 17:19:43 GMT test/core/byoa/test_fileset.py ...........                               [  9%]
Mon, 11 Mar 2024 17:19:43 GMT test/core/gen/test_config.py ......                                      [  9%]
Mon, 11 Mar 2024 17:54:01 GMT test/core/gen/test_gen.py ...............                                [ 10%]
Mon, 11 Mar 2024 17:54:01 GMT test/core/gen/test_iproc.py .......                                      [ 11%]
Mon, 11 Mar 2024 17:54:07 GMT test/core/gen2/local/test_generator.py ......                            [ 11%]
Mon, 11 Mar 2024 17:54:07 GMT test/core/gen2/local/test_helpers.py ..                                  [ 11%]
```

**To Reproduce**
1. Run the xcube ‘Unittest and docker builds’ workflow in GitHub Actions, or look at one of the [previous runs](https://github.com/dcs4cop/xcube/actions).
2. Display the logs for the `unittest` step and activate timestamps.
3. Observe that `test_gen.py` takes over half an hour.

**Expected behavior**
`test_gen.py` on GHA completes in seconds or tens of seconds (as it already does on other platforms), rather than in tens of minutes.

**Comment by konstntokas** [comment]
I profiled the module `test/core/gen/test_gen.py` and compared the results in CI pipeline and on the local machine. 

[**github pipeline**](https://github.com/xcube-dev/xcube/actions/runs/9081133714/job/24954235937): 
![Screenshot from 2024-05-15 08-29-53](https://github.com/xcube-dev/xcube/assets/38956538/93462761-ed4a-4995-9a9c-48621f4e5efa)


**local pipeline:** 
![Screenshot from 2024-05-15 08-51-18](https://github.com/xcube-dev/xcube/assets/38956538/31e5dccb-c3ac-47a2-8301-653a9290449d)
![Screenshot from 2024-05-15 08-51-43](https://github.com/xcube-dev/xcube/assets/38956538/e536c0ba-c8b7-4414-9cfb-06d49085448f)


**What did I notice so far:** 

- the fuction `_compute_ij_images_for_source_line()` in `xcube/core/resampling/rectify.py` consumes a lot of time which is not shown on the profiling result on the local machine for the first 1000 entries. `Numba` is used to parallelize the for loop. I assume that something goes wrong with `numba` in the CI pipeline.

**Comment by konstntokas** [comment]
In the next step I remove `numba` in the `xcube/core/resampling/rectify.py`

**[github pipeline profiling](https://github.com/xcube-dev/xcube/actions/runs/9092212406/job/24988434199):**
![Screenshot from 2024-05-15 11-09-40](https://github.com/xcube-dev/xcube/assets/38956538/4ec585d9-d638-4a7a-933b-25facd71af98)


**Local profiling**
![Screenshot from 2024-05-15 11-10-05](https://github.com/xcube-dev/xcube/assets/38956538/16e8a48e-946e-4da7-87f8-f68ccaecceb1)
![Screenshot from 2024-05-15 11-10-22](https://github.com/xcube-dev/xcube/assets/38956538/27b435e9-3679-41a0-b165-1e9d6bec0013)

**What did I notice:**
- The CI pipeline is not slower
- The local testing got a lot slower and consumes now a lot of time in `_compute_ij_images_for_source_line()`.

**Conclusion**
Something goes wrong with the parallelization using `numba` -> I will investigate that further

**Comment by konstntokas** [comment]
**Cause**
`NUMBA_DISABLE_JIT` is set to `1` in [xcube_workflow.yaml#L17](https://github.com/xcube-dev/xcube/blob/main/.github/workflows/xcube_workflow.yaml#L17), which disables `numba.jit`. 

**Solution**

- set `NUMBER_DISABLE_JIT: 0`
- remove `env: NUMBA_DISABLE_JIT: 1`
