### ISSUE TITLE
xcube plugins not auto-recognized when using `pyproject.toml`

### ISSUE THREAD

**Issue by forman** [xcube-dev/xcube#963]
**Describe the bug**

xcube plugin packages are not automatically recognized as xcube plugins 

1. although the package name is prefixed using `xcube_`;
2. if installed via `pip -e .`;
3. if using a `pyproject.toml` rather than `setup.py`.

**To Reproduce**

See plugin [xcube-cmems](https://github.com/xcube-dev/xcube-cmems) that is forced to explicitly declare the entry point `xcube_plugins` in its `pyproject.toml`. 

**Expected behavior**

Packages named `xcube_<name>` should automatically be recognized as xcube plugins.

**Comment by konstntokas** [comment]
The function [_collect_plugins(list(iter_ent...](https://github.com/xcube-dev/xcube/blob/main/xcube/util/plugin.py#L101) finds the entry points. Therefore if the entry point is given explicitly in the pyproject.toml, it will find the xcube_cmems plugins. 

The function [_collect_plugins(discover_plu...](https://github.com/xcube-dev/xcube/blob/main/xcube/util/plugin.py#L110C9-L110C25) iterates through the installed packages in the site-package folder of the environment. If xcube_cmems is installed with `pip install -e .`, the xcube_cmems folder is not put in the site-package folder of the environment. Therefore xcube_cmems can not be found. If xcube_cmems is installed with `pip install .` , the xcube_cmems folder is not put in the site-package folder of the environment, and the plugin is recognized.

**Comment by forman** [comment]
That is actually known. The issue is that now that we use the `pyproject.toml` the detection by name no longer functions. Before using `pyproject.toml` we used `setup.py`, which worked.

**Comment by konstntokas** [comment]
This is an issue with the `pyproject.toml`file in [xcube-cmems](https://github.com/xcube-dev/xcube-cmems). Discussion continues at xcube-dev/xcube-cmems#39

**Comment by konstntokas** [comment]
**What does setuptools during editable installs**

Using setuptools within `pyproject.toml` creates `__editable__.<package>-<version>.pth` in the `site-packages`folder, which gives information on the path to the package. (See https://setuptools.pypa.io/en/latest/userguide/development_mode.html). This is done in two different ways depending on the project structure (See https://discuss.python.org/t/help-testing-pep-660-support-in-setuptools/16904/44?page=3).

- If src/ layout is used, the `__editable__.<package>-<version>.pth` is static and contains the path to the packages, which is added to `sys.path`and therefore the package can be found by [pkgutil.iter_modules()](https://github.com/xcube-dev/xcube/blob/main/xcube/util/plugin.py#L76). Therefore the plugin is recognized. 
- If a flat hierarchy is used, like we do in all of the projects,  `__editable__.<package>-<version>.pth` is dynamic and the python script `__editable___<package>_<version>_finder.py` is added. Hereby, a path hook is added to `sys.path` (https://setuptools.pypa.io/en/latest/userguide/development_mode.html), which adds the path to the package during `import`, but this can not be resolved by [pkgutil.iter_modules()](https://github.com/xcube-dev/xcube/blob/main/xcube/util/plugin.py#L76). Therefore the plugin is not recognized. 

**Solution**

Resolve the package name from the `__editable__.<package_name>-<version>.finder.__path_hook__` file in [discover_plugin_modules](https://github.com/xcube-dev/xcube/blob/main/xcube/util/plugin.py#L73C5-L73C28).

**Comment by forman** [comment]
@konstntokas, thanks for the investigation!
