### ISSUE TITLE
STAC and coverages endpoints are duplicated in OpenAPI page

### ISSUE THREAD

**Issue by pont-us** [xcube-dev/xcube#965]
For compatibility with a range of clients, STAC and coverages endpoints need to support URLs both with and without a trailing slash. Due to time pressure during OGC Testbed-19, this was implemented very simplistically by adding an extra `api.route` decorator to the implementations, e.g.

```python
@api.route(PATH_PREFIX + "/collections")
@api.route(PATH_PREFIX + "/collections/")
class CatalogCollectionsHandler(ApiHandler[StacContext]):
    …
```

In source code this is non-DRY, and in deployment it has the unfortunate effect of duplicating the generated OpenAPI documentation for every endpoint:

![aaaaaaa](https://github.com/xcube-dev/xcube/assets/9010180/6e5c0ce6-a515-4e40-adc6-825f18ca943a)

Slash / no-slash handling should be implemented in a way that avoids cut-and-paste source code and duplicated OpenAPI entries.

**Comment by forman** [comment]
My preferred solution:

```
@api.route("ogc/collections/{collectionId}/coverage", slash=True)
class CoveragesCoverageHandler(ApiHandler[CoveragesContext]):
    ...
```

where `slash=True` adds an internal (!) second route with a trailing slash or it causes a redirect. For implementation <https://www.tornadoweb.org/en/stable/web.html#tornado.web.addslash> and <https://www.tornadoweb.org/en/stable/web.html#tornado.web.removeslash> might be useful.
